# Generated by Django 4.2 on 2023-06-27 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0004_tokenlifetimeexpired'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenLifetimeExpired',
        ),
    ]
