# Generated by Django 4.2.2 on 2023-07-10 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema_app', '0006_alter_moviesession_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesession',
            name='image',
        ),
        migrations.RemoveField(
            model_name='moviesession',
            name='image_title',
        ),
    ]
